# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastagent-hacking',
                'doc_host': 'https://achrafmam2.github.io',
                'git_url': 'https://github.com/achrafmam2/fastagent-hacking',
                'lib_path': 'fastagent_hacking'},
  'syms': {'fastagent_hacking.core': {'fastagent_hacking.core.foo': ('core.html#foo', 'fastagent_hacking/core.py')}}}
